#ifndef DESCRIPTOR_H
#define DESCRIPTOR_H

#include "types.h"

enum DESCRIPTORACCESS
{
	DA_ACCESSED = 1,
	DA_WRITEABLE = 2,
	DA_EXPANDDOWN = 4,
	DA_EXECUTABLE = 8,
	DA_CODEDATA = 16,
	DA_RING0 = 0,
	DA_RING1 = 32,
	DA_RING2 = 64,
	DA_RING3 = 96,
	DA_PRESENT = 128,

	DA_GATE_INVALID = 0,
	DA_GATE_AVAIL286TSS = 1,
	DA_GATE_LDT = 2,
	DA_GATE_BUSY286TSS = 3,

	DA_GATE_286CALLGATE = 4,
	DA_GATE_TASKGATE = 5,
	DA_GATE_286INTRGATE = 6,
	DA_GATE_286TRAPGATE = 7,

	DA_GATE_INVALID2 = 8,
	DA_GATE_AVAIL386TSS = 9,
	DA_GATE_RESERVED = 10,
	DA_GATE_BUSY386TSS = 11,

	DA_GATE_386CALLGATE = 12,
	DA_GATE_RESERVED2 = 13,
	DA_GATE_386INTRGATE = 14,
	DA_GATE_386TRAPGATE = 15
};

enum DESCRIPTORFLAG
{
	DF_DEFSIZE = 4, DF_GRANULARITY = 8
};

#define DA_KRNINTR (DA_PRESENT | DA_GATE_386INTRGATE)

#define GDT_ADDR (DESCRIPTOR *)0x10006
#define IDT_ADDR (DESCRIPTOR *)0x406

#define KRN_SEG_CODE 0x08
#define KRN_SEG_DATA 0x10 

typedef word DESCRIPTORINDEX;
typedef word SELECTOR;

void ltr(SELECTOR selector);
SELECTOR str(void);

void descriptor_set(const DESCRIPTOR *desc_table,
		const DESCRIPTORINDEX desc_idx, const DESCRIPTOR* desc);
void descriptor_get(const DESCRIPTOR *desc_table,
		const DESCRIPTORINDEX desc_idx, DESCRIPTOR* desc);

#endif /*DESCRIPTOR_H*/
